version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mp_sqlserver
    environment:
      SA_PASSWORD: "Max_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ 
        "CMD-SHELL", 
        "/opt/mssql-tools/bin/sqlcmd -U sa -P Max_password123! -Q \"SELECT 1\""
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    build:
      context: .
      dockerfile: MaxProcess.API/Dockerfile
    image: maxprocess_api:latest
    container_name: mp_api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MaxProcessDb;User Id=sa;Password=Max_password123!;TrustServerCertificate=True
    depends_on:
      sqlserver:
        condition: service_healthy